{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "jni-swig-stub",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q3e2rgg2l5byhb7nda4kjixyhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jni-swig-stub-0.0.1-SNAPSHOT.jar",
          "url": "jni-swig-stub-0.0.1-SNAPSHOT.jar",
          "size": 47558,
          "sha512": "13c90bf1938f3aa5338a6045adaea8a6134264fd76f8af00bb0aed9cff801c4960698f132ef4b6c750607df3bb9fa87cd641fb183a1e0be89886f18ac2f34e3d",
          "sha256": "742e0d49ece5c19f54b1bf15f0d77cbd7a3a3145058108c36da25eedc356b010",
          "sha1": "65627694fb48cd252c84cefdb9e44c568724d84f",
          "md5": "cdf09d0590f37ff22229b92371e81cd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jni-swig-stub-0.0.1-SNAPSHOT.jar",
          "url": "jni-swig-stub-0.0.1-SNAPSHOT.jar",
          "size": 47558,
          "sha512": "13c90bf1938f3aa5338a6045adaea8a6134264fd76f8af00bb0aed9cff801c4960698f132ef4b6c750607df3bb9fa87cd641fb183a1e0be89886f18ac2f34e3d",
          "sha256": "742e0d49ece5c19f54b1bf15f0d77cbd7a3a3145058108c36da25eedc356b010",
          "sha1": "65627694fb48cd252c84cefdb9e44c568724d84f",
          "md5": "cdf09d0590f37ff22229b92371e81cd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni-swig-stub-0.0.1-SNAPSHOT-sources.jar",
          "url": "jni-swig-stub-0.0.1-SNAPSHOT-sources.jar",
          "size": 36957,
          "sha512": "e2524ba81601c7d15398c3937d8dfbca31c4d5260647a11e2c81bfeccca295ca174c8b5063bbb9cdaa7492e637de69c2b840e1a83329cd8bbf3514db11024dea",
          "sha256": "24af191a3ecd8da3961b834ba0a15da9892637cb618813d0f7bde67946fb92e0",
          "sha1": "52f73dd40afb39475d7e0ea4d7f433ce7f961760",
          "md5": "532ec4a2c6988809e05e2feaefe068f2"
        }
      ]
    }
  ]
}
