{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "kltrgtvdevbihbmiyt3w5dggpy"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-release.aar",
          "url": "library-android-0.0.1-SNAPSHOT.aar",
          "size": 30876,
          "sha512": "5ed5770179d364da590fc9ee2d630fe5faf7142e29922905eabf68c95efb031a90db62e4e8e586654e1701643d8cc7eda75334274b61d47fe411c3685fb54388",
          "sha256": "0bed3f81a21ae75d6cb45339d627fb189167ff98aa45f3f88942d5f50bf0831b",
          "sha1": "b44a1fe51a1f00d5b7c4936ed8297f6479ac51b2",
          "md5": "e17d836736cb44dbcb56c10c660e06f7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-release.aar",
          "url": "library-android-0.0.1-SNAPSHOT.aar",
          "size": 30876,
          "sha512": "5ed5770179d364da590fc9ee2d630fe5faf7142e29922905eabf68c95efb031a90db62e4e8e586654e1701643d8cc7eda75334274b61d47fe411c3685fb54388",
          "sha256": "0bed3f81a21ae75d6cb45339d627fb189167ff98aa45f3f88942d5f50bf0831b",
          "sha1": "b44a1fe51a1f00d5b7c4936ed8297f6479ac51b2",
          "md5": "e17d836736cb44dbcb56c10c660e06f7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
