{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "mivlqka25ngh7cpqpg7nkmxgeq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 35854,
          "sha512": "56ebf4493bf6641b44226d4776dd311dca44aab07b305099097bf7f5ac2c9997ed94d07117721f53956b23d5fac8b7deb3eedbbf572304d264eb85abf3652034",
          "sha256": "0f5cb8ce0e6df8290c9bcaae7b51a160250dc1ea253383338a9a8c25ebc351f5",
          "sha1": "7088367213e0bc278480070d01e0c83e0ad85d19",
          "md5": "7226aecc44caf04e60bcc9a880337287"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 35854,
          "sha512": "56ebf4493bf6641b44226d4776dd311dca44aab07b305099097bf7f5ac2c9997ed94d07117721f53956b23d5fac8b7deb3eedbbf572304d264eb85abf3652034",
          "sha256": "0f5cb8ce0e6df8290c9bcaae7b51a160250dc1ea253383338a9a8c25ebc351f5",
          "sha1": "7088367213e0bc278480070d01e0c83e0ad85d19",
          "md5": "7226aecc44caf04e60bcc9a880337287"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
