{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5bzl6lpmkjc5npvscs26gj5b7u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 39715,
          "sha512": "7916c8279602c2f37d469807484092f444648fae5a39af6f7e93e881d541cdd6352a53ed38d223a6b38f51a40541e4aac7d880708f3e6aaba5e25843e9d9ed60",
          "sha256": "6c8df8bf07749511bae875664204a44698d4601a7c1ad6f1aba5f9c5f69a89aa",
          "sha1": "0ed2943fa9effaac556c59ad7a9b9eda2bfb8e6f",
          "md5": "8305e51a0304ae6c2bfc7c5285409b68"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 39715,
          "sha512": "7916c8279602c2f37d469807484092f444648fae5a39af6f7e93e881d541cdd6352a53ed38d223a6b38f51a40541e4aac7d880708f3e6aaba5e25843e9d9ed60",
          "sha256": "6c8df8bf07749511bae875664204a44698d4601a7c1ad6f1aba5f9c5f69a89aa",
          "sha1": "0ed2943fa9effaac556c59ad7a9b9eda2bfb8e6f",
          "md5": "8305e51a0304ae6c2bfc7c5285409b68"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
