{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "m7attuko7vcgfgg46equzi2x2u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 24371,
          "sha512": "863f8692a7b4484e52efd42bfd44dad00ea5af658eca7552b6e19b8baf90ab17dc0a2963804bc159a6cf958a33f9c00c28c1ce1e23dbca53b982ff1fc1476662",
          "sha256": "08ba27796438adc788b54b015ac32095c97026342f4bec4084cd69095f4aabf9",
          "sha1": "ca560784fbf3a0c71c7e0d0fbb2e2ac2adfcd3d0",
          "md5": "cec604ecd6d6c4aa18e52dbcaf592dfe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 24371,
          "sha512": "863f8692a7b4484e52efd42bfd44dad00ea5af658eca7552b6e19b8baf90ab17dc0a2963804bc159a6cf958a33f9c00c28c1ce1e23dbca53b982ff1fc1476662",
          "sha256": "08ba27796438adc788b54b015ac32095c97026342f4bec4084cd69095f4aabf9",
          "sha1": "ca560784fbf3a0c71c7e0d0fbb2e2ac2adfcd3d0",
          "md5": "cec604ecd6d6c4aa18e52dbcaf592dfe"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
