{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "unys7ihl7fenjjldtuzztjtcr4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 42700,
          "sha512": "843c52514c4c9b0511e00e9b11023d0a855fbb99772d1adc069a1005190fb605cc8b036bd2a3fa5c402125d6d250f2005bc75d09b0c0c97ba0ff2273d5b6fa69",
          "sha256": "0cc71644d8a56aeb6c3ecd388e2576505d57a667720bf644350fe65233e25b4b",
          "sha1": "2ed8684ae53295648839e2d6f9162ec7c5691aa4",
          "md5": "830e24797b572c8c0e3cac603cbe115c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-jvm-0.0.1-SNAPSHOT.jar",
          "size": 42700,
          "sha512": "843c52514c4c9b0511e00e9b11023d0a855fbb99772d1adc069a1005190fb605cc8b036bd2a3fa5c402125d6d250f2005bc75d09b0c0c97ba0ff2273d5b6fa69",
          "sha256": "0cc71644d8a56aeb6c3ecd388e2576505d57a667720bf644350fe65233e25b4b",
          "sha1": "2ed8684ae53295648839e2d6f9162ec7c5691aa4",
          "md5": "830e24797b572c8c0e3cac603cbe115c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
