{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ltcoksvf6jgw5ij6dwsxxjziiu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 2525,
          "sha512": "99196c0fd90293cf14616a77a5a3194e3aea5a425da500418c19815d2a534760908c94d155062c859dced223b4aa8f701658753d4b29e886bae323d794544192",
          "sha256": "8c4f6aea2b81238b7bfd9e9e8efa6b845f8f4f259f6047fe5f43f6008b992788",
          "sha1": "499af9fb5cbdf365aafdf1bee4aa2c8ca7a9c07f",
          "md5": "4833ac036887b7a3bb97a90fb8087324"
        }
      ]
    }
  ]
}
