{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6bvzy6ueanetjgcafacnxzaapa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 2525,
          "sha512": "777c30a1707acaeff9ec04b74174fe7f2f1e6571143269524c5d5855985f2384e687983f448874f0f8315e2607511ef8dbebce644b727bcf5cf6935b1d1f0a86",
          "sha256": "b31fac332b88b3e14613bcd8c13713513a531e1fed78e175139acc89371200d0",
          "sha1": "0d5d4ca345c04251293f68adcc93da59c4c65375",
          "md5": "3504eab06d82e5c3c540b7e5980db325"
        }
      ]
    }
  ]
}
