{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "proci3g3ibbk3ozhbrxcts6k6y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 3507,
          "sha512": "8e1961c2a02a561b1c88df310e0fa1af2193c07eeb6aa8fdc5d354bfc591acca829858c2a840636f0f5fcb3b32e5a83dcd157203d4730a6e34ac47be37a61fc8",
          "sha256": "a5693b5d67a6b56fdd91c52b71b88d358efa8cf8845aa21d62e5d735d0cc5c85",
          "sha1": "ba3e50ed160188b56cce3a4a553740da68939ee2",
          "md5": "157dfddb7afa762432e83156387176c8"
        }
      ]
    }
  ]
}
