{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "m7attuko7vcgfgg46equzi2x2u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 3507,
          "sha512": "8291f7f832b330d8f9229792a524cf48520fbea39decd60dc981b007e09a2921294e3a7b8606ea4fbff11f13d665a7a230bd8ae3efa885f7903fe5240b7db5d0",
          "sha256": "e915b4c3bf7836c8faa318995856c4901957b49ae8c7738488342e5188e619a0",
          "sha1": "076f7e2ca96f06c0c9bf184d96c7a5d2f05543eb",
          "md5": "69e3d45bc2d8d78ebb75864a71287a6b"
        }
      ]
    }
  ]
}
