{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6egzcbczdzd5dhwgb5brpaofaa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 3507,
          "sha512": "7a7d91a4d60ed14f06c5e9df7489940dee4ce8c3e339caeeba0804c692c419d5652e333c76d58a68e20ba38238f170dc8a9072a63fe2f7671578cbe49f13ac6e",
          "sha256": "628890806f0c5aa521d800bb4c2e5675fc9cd32f481fd04318b581634d681a1b",
          "sha1": "d07ae279e505ddcdea3bbe563bd56f7760945ff9",
          "md5": "594cb1c5947d3706aa2c55a43d625ecb"
        }
      ]
    }
  ]
}
