{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "uq7ommsvp5guxexm5cq4ktna7y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 2525,
          "sha512": "442cf04c32e0babe9bd669041419e052b5529f4fc3edefe5e7ebe2750dd48121122789a4f29eeb66e935ce040a6075e62bcfc7da25495e7a517145ff05289d93",
          "sha256": "b6cd6d614dc691d71c9823c1fb249590d449e116c94787c0ea9ef1ec69b7be3a",
          "sha1": "d7e87e343e19d45d6f22f405c99ac7c994ee8a4f",
          "md5": "8939ab4f577e7fe3b9c0c4f3187ee517"
        }
      ]
    }
  ]
}
