{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "w3fetr7k75hzrmrc26cp5x4fre"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 3193,
          "sha512": "342d1dc37cea6d38c9112efecb459dc10cf0d622b241f65b9400894c6069a58769d1d31a61246ff765cd74f4b7992b14721495754a1673b326bc57d6719e287c",
          "sha256": "03e68942cda9059369e05186d4fe97b1a45d0a261f88322774182d9f8f20e6ae",
          "sha1": "311d44c8abd77c6b7521800de7dbc65f0afc49f7",
          "md5": "a14510100b47bbb5f46a66b602056eed"
        }
      ]
    }
  ]
}
