{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "vykrpmz2cbhv7gnbavz5564v7i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "size": 3193,
          "sha512": "c1989a5efaab5295393d5f59dd7ccbf0a237734e0a35026b4f56a895d9e759d88c939f6d3665767b6fd43f8b60969703086f8a9036cc57af1420cbd8ba770244",
          "sha256": "3b255fa4ef39d1327aaec107344337f74c918b016fbed352fa999d5d4a2525d3",
          "sha1": "a3b166a4b74de71142b4c4f507d7456617266aba",
          "md5": "63abc37eb28e2debeea7688e59794e32"
        }
      ]
    }
  ]
}
