{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "w3fetr7k75hzrmrc26cp5x4fre"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 4733,
          "sha512": "4caa86d508d1bece75e5b4657b60c264ca6c55ca0d7a189d57cc3de29822241566d922bc3b499d2ef1450b16a0c46c86b4d0b9c2a6e2a614f42c1b5f85a630be",
          "sha256": "f48ee8af610be7f6821421f34ff2b088fa3754728dfe1a0b1b1669b23a22b1e2",
          "sha1": "57b2530033939513e5fe7caf2a96c561ec5aef42",
          "md5": "8812f6a5ab2da9cf70898f0775382e63"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 4733,
          "sha512": "4caa86d508d1bece75e5b4657b60c264ca6c55ca0d7a189d57cc3de29822241566d922bc3b499d2ef1450b16a0c46c86b4d0b9c2a6e2a614f42c1b5f85a630be",
          "sha256": "f48ee8af610be7f6821421f34ff2b088fa3754728dfe1a0b1b1669b23a22b1e2",
          "sha1": "57b2530033939513e5fe7caf2a96c561ec5aef42",
          "md5": "8812f6a5ab2da9cf70898f0775382e63"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
