{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jqmqxvrrbbhjbbrmh4jiwykdbu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 5463,
          "sha512": "2a179e7bc33544e3db1ec221cddd0abe3cdad354cd516b06fad73e02d2dca502e137157ff67b1b66135ada83a5783717ef2463f0a5e4a553a98ed85ae51c9631",
          "sha256": "aff1682eeb888950e68b0b77f4ad1e97d8df0aa2566c722f7b9d3c7066356f76",
          "sha1": "8971b4f35e3e6f3a614b167bd1543facce085734",
          "md5": "f51c00476aab25f86c2f7c9b0b9bcc7e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 5463,
          "sha512": "2a179e7bc33544e3db1ec221cddd0abe3cdad354cd516b06fad73e02d2dca502e137157ff67b1b66135ada83a5783717ef2463f0a5e4a553a98ed85ae51c9631",
          "sha256": "aff1682eeb888950e68b0b77f4ad1e97d8df0aa2566c722f7b9d3c7066356f76",
          "sha1": "8971b4f35e3e6f3a614b167bd1543facce085734",
          "md5": "f51c00476aab25f86c2f7c9b0b9bcc7e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
