{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "qcylm4rwr5eyhpak4l5ryncdfi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 5463,
          "sha512": "792992d3dba15cf184e8d161cac4cefad232a2ce9b3481851a165acb7b72c860ed3e65328b227bcb4bf779e896e77fcc5ba5146646f9d5cbf5091ae54b50cf9e",
          "sha256": "4ed8259d6e7cb756ea1ce3bc8d6c3bc3ffc607c53628c4782e4e2ffd53ba475b",
          "sha1": "4f35d6f4a23c9f6211a165be7ea214eafd1a2951",
          "md5": "777d759b205ebba2fa0119b7b3147561"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 5463,
          "sha512": "792992d3dba15cf184e8d161cac4cefad232a2ce9b3481851a165acb7b72c860ed3e65328b227bcb4bf779e896e77fcc5ba5146646f9d5cbf5091ae54b50cf9e",
          "sha256": "4ed8259d6e7cb756ea1ce3bc8d6c3bc3ffc607c53628c4782e4e2ffd53ba475b",
          "sha1": "4f35d6f4a23c9f6211a165be7ea214eafd1a2951",
          "md5": "777d759b205ebba2fa0119b7b3147561"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
