{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6bvzy6ueanetjgcafacnxzaapa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 3893,
          "sha512": "52f576cec92dfbc4e803304a8f024fef98e60698170e228cd1acbd74a233daff0fc73b93f2c075b9331a4118c3192348bed1d56fb4f18e073fcd85535867d47f",
          "sha256": "87e40e94623e1f29a3f9904a3503f45d6ef54477fcffb2c9f3cc4752e05bb82b",
          "sha1": "e1520f57f8c8c4e3062089002ed57f0f4de8b6b1",
          "md5": "8f4ee21fd13dbea2444eab504e50af93"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 3893,
          "sha512": "52f576cec92dfbc4e803304a8f024fef98e60698170e228cd1acbd74a233daff0fc73b93f2c075b9331a4118c3192348bed1d56fb4f18e073fcd85535867d47f",
          "sha256": "87e40e94623e1f29a3f9904a3503f45d6ef54477fcffb2c9f3cc4752e05bb82b",
          "sha1": "e1520f57f8c8c4e3062089002ed57f0f4de8b6b1",
          "md5": "8f4ee21fd13dbea2444eab504e50af93"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
