{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "4dyxnyw7d5djnek6oe7u6ph634"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 3893,
          "sha512": "9496842dbab33d0a2699a2001760c3a91a88c15aa1909fb3cfbea49c693d28f9d4e1b881fa828cfd5d1e74865d2c4351b75b8b117daef5a70d2644bdf61e55f1",
          "sha256": "3cb3b6df6bef6d7f4c5bc4e1be1678fa9e51dffb8f21539a6824d59adea20152",
          "sha1": "c7205b81664c5f8eda9d262af60a81fe4e1fdf86",
          "md5": "f7cdd9dd2fc8183cfa872cc2094a58ca"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-jvm-0.0.1-SNAPSHOT.jar",
          "size": 3893,
          "sha512": "9496842dbab33d0a2699a2001760c3a91a88c15aa1909fb3cfbea49c693d28f9d4e1b881fa828cfd5d1e74865d2c4351b75b8b117daef5a70d2644bdf61e55f1",
          "sha256": "3cb3b6df6bef6d7f4c5bc4e1be1678fa9e51dffb8f21539a6824d59adea20152",
          "sha1": "c7205b81664c5f8eda9d262af60a81fe4e1fdf86",
          "md5": "f7cdd9dd2fc8183cfa872cc2094a58ca"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
