{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6egzcbczdzd5dhwgb5brpaofaa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 2905,
          "sha512": "5a6d1bafe57f8622f1e31b20b5a9a35c069b3a735c8b3b41163c663bfd185c02b5ccccc5cf2483df90fdf98c2a0159b32eacfe6213b19d74791ffc20107df17e",
          "sha256": "7946ddec25c3309474011286d5e6a7bf70d41ea5081ac9880581593e50691d9e",
          "sha1": "d44e7bab347f5784d70234a63cfec754ace45d67",
          "md5": "fc55c5a9dc7b5a56fe47c165f07490cd"
        }
      ]
    }
  ]
}
