{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "m7attuko7vcgfgg46equzi2x2u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 2905,
          "sha512": "678139d977547c31f9f183dab264e7426513ddacf601c924a3dd79c1dc6b52c3b8d7aa38e3df93c83dc7ad418cad17ee523fcf9cecfcc5469ecaa88a82bc7a53",
          "sha256": "2d6dc3671603646f892c29f28c297078993c593fc5a9fa65813b5390905273f7",
          "sha1": "e5169a1d857796898410845565ff6faac6ca8561",
          "md5": "00635fb16f2f3449e5a233748eaa8797"
        }
      ]
    }
  ]
}
