{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "bo52bpk54nbnpndfkstmfh35iq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 7664,
          "sha512": "7cd4678ce08c5fc290e9f1e57d3a485abcd47b5a509ad5b4dfd5162cfd950e18ce25c4c1c94c3cad7fc846acf58897550a9698742f88c28198d99ea5bdb4bf57",
          "sha256": "35b033b13aa5a48e2aa9b653a51d240972d05111c342e7fda010a065d0daeee7",
          "sha1": "db58cb4e93dfc2a26b691c09854d88b5f606298c",
          "md5": "a2b234f826b3765fdbbec32426b7fa54"
        }
      ]
    }
  ]
}
