{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fk47hhp4wbad3eupfhvtksvz2i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 11416,
          "sha512": "3baf1bb5dbfc9241f2358b65117bb612d8c340e9cd5c632f52b8cc424b46e94ae18bed4ec176db942c67ab7a4f6caa28fdc1c9e7bd8831036b86f8b67375d80b",
          "sha256": "a5967871f86223af19c28b3fc40d7cd9c1d4c9cf6d32ba5cf417fb501f982975",
          "sha1": "ca0808e9d2d12d33baf3eaa392a7c611b2fb0419",
          "md5": "1c9ef3132796736ba9dc6125b62765b4"
        }
      ]
    }
  ]
}
