{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "rzgj3lv7offm3momvbfwacf7de"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 10232,
          "sha512": "0d861d0d836b7ec85f225ebefc475abece06b1727941216a44e526ba61d00a1866e1b5b9a2b4c8e156a8a8d806ea21c289a7faa71f9c85aa47308480e902badf",
          "sha256": "0c8cf6603d77e6eff88607c3908b7d5bf6e44422afc4b1529b7cb04995e64ab0",
          "sha1": "7a0d2146e3a1dd249e8f8b41fc15d936421b4f4a",
          "md5": "16f764bd04bf35722402ed6cfa6a20df"
        }
      ]
    }
  ]
}
