{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "unys7ihl7fenjjldtuzztjtcr4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 4361,
          "sha512": "b20685675e4a7a98ab60e8eefbda0dfa65c811ff78262c9219c6eba9e13742928bebb683e9cf1abc0afe266f174c2ee5e57f7d9ba6485a08c5f0fa7858083105",
          "sha256": "c705bdf80808a9f4547d7f94a91d9d162755cdf64c28150bfe53f4cc81f1ec31",
          "sha1": "46ee431ede365e5f8399ee77389eee6c3227eb4e",
          "md5": "57948375c0ae9771563948a0715eb12c"
        }
      ]
    }
  ]
}
