{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library-macos/0.0.1-SNAPSHOT/library-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "gtko3sey4rcstpjkqkzlc6bzxu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 7094,
          "sha512": "e53564e2e19ab8a1d158e0bf4cc56aad1229e2a54ef20211c6375493cd022aae51c6430ed2f20e50701d5dce331785ddc9b70587f78b333b75956cf0cfdcf202",
          "sha256": "4ef2768d11bf4af204ed3113e121c82435d6362a8415e0049eab8b24f432b06e",
          "sha1": "435beee30d82c1c1f5bcf0e726eb3acb0a7a7d44",
          "md5": "c0ee88a0a3c31b2e14e2b47a624431dd"
        }
      ]
    }
  ]
}
