{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lztqx75agbddbhe2qy3uqras4y"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 24919,
          "sha512": "624f2c4b6e7995b57e56fc9e9bbd4d618e5ab1a6102638018f4eaa08c141513e440a81d642dfb5fe5ea9ac7f14633189691e114ffcee3384bd3fb3659f78d0fe",
          "sha256": "99b5c0f8cf485be0ef1799a9916a312b41f1f55444b9c9bc0870c00b40714873",
          "sha1": "43c6c4caeb1d5e11a7602bc40d097c3b2bba4e70",
          "md5": "e90300989cd04ac8d5a7e0d4c07a83d0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 24919,
          "sha512": "624f2c4b6e7995b57e56fc9e9bbd4d618e5ab1a6102638018f4eaa08c141513e440a81d642dfb5fe5ea9ac7f14633189691e114ffcee3384bd3fb3659f78d0fe",
          "sha256": "99b5c0f8cf485be0ef1799a9916a312b41f1f55444b9c9bc0870c00b40714873",
          "sha1": "43c6c4caeb1d5e11a7602bc40d097c3b2bba4e70",
          "md5": "e90300989cd04ac8d5a7e0d4c07a83d0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
