{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ifh4kenyvjenhdje3a3eqlo2km"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 33717,
          "sha512": "583d537bdc9509004ebf149bc69cfb203371c74115afe56caf161e91ac7d255dab1825033a94bbdfa2ff8929edad5728abc7c7b5b76e8fab5e601e658d4ca4b4",
          "sha256": "6cd2ee8ad7f02120351cad9b7a7be6b60ac66c7e6b05d05d609162b90b174fdb",
          "sha1": "4608abba36e5803983a18673c32bfaab06406c38",
          "md5": "a58a62c5b90933565cf763a3e9ae41e9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 33717,
          "sha512": "583d537bdc9509004ebf149bc69cfb203371c74115afe56caf161e91ac7d255dab1825033a94bbdfa2ff8929edad5728abc7c7b5b76e8fab5e601e658d4ca4b4",
          "sha256": "6cd2ee8ad7f02120351cad9b7a7be6b60ac66c7e6b05d05d609162b90b174fdb",
          "sha1": "4608abba36e5803983a18673c32bfaab06406c38",
          "md5": "a58a62c5b90933565cf763a3e9ae41e9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
