{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "somvrmu74revpa67xwwsm5fbn4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 32284,
          "sha512": "25b9315a4049407723a4b311a829abf86f5608646e63d3257a7d40f0e2703ddcb036af2588f352e9e616ae0c9dd43e82eaab91e5b7b4434637ee88db19234e76",
          "sha256": "08477c09debb98c53065de68cef1aa1557fd80f2849942619d25119776c9e8d4",
          "sha1": "9c5d757cf2f0db483b2e268d22f1dc552744ee77",
          "md5": "58794b59babe40aaf75f766e62f49b83"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 32284,
          "sha512": "25b9315a4049407723a4b311a829abf86f5608646e63d3257a7d40f0e2703ddcb036af2588f352e9e616ae0c9dd43e82eaab91e5b7b4434637ee88db19234e76",
          "sha256": "08477c09debb98c53065de68cef1aa1557fd80f2849942619d25119776c9e8d4",
          "sha1": "9c5d757cf2f0db483b2e268d22f1dc552744ee77",
          "md5": "58794b59babe40aaf75f766e62f49b83"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
