{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "rcev5xwx4velhhbk5opwucnzdu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 32284,
          "sha512": "45df19c4111b6149aef042712f0735e29e1e31398cd1d9fe9cc27d6ab217a556efb875a661e2f3caa65d6590df71ded4d2b9238212047460dd218f0fae267838",
          "sha256": "d89e0cc54adf570e003ad6c379cf5d1994c3fc47d0354cd73132f4321126f353",
          "sha1": "644a3100d9bb6e85b5af067fc117957ebe0bdfa5",
          "md5": "9a0039a1a9a362d4e4ba256622d72909"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 32284,
          "sha512": "45df19c4111b6149aef042712f0735e29e1e31398cd1d9fe9cc27d6ab217a556efb875a661e2f3caa65d6590df71ded4d2b9238212047460dd218f0fae267838",
          "sha256": "d89e0cc54adf570e003ad6c379cf5d1994c3fc47d0354cd73132f4321126f353",
          "sha1": "644a3100d9bb6e85b5af067fc117957ebe0bdfa5",
          "md5": "9a0039a1a9a362d4e4ba256622d72909"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
