{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lztqx75agbddbhe2qy3uqras4y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 5745,
          "sha512": "642eee021b7c6eee914f165c6b4ba66f5891814b252baf8a920c4d184f730d16ce466749a30d91dbf560704e0832ea5b0e5463235466a9038f162a64e887fa44",
          "sha256": "cced8a30af0c92271e60d4a93094f90e6277c2b8520f6ec0e51ce93c37fbd586",
          "sha1": "ce51a69e81493dd4284d56d36992425d4cc248c0",
          "md5": "517a5a50bce32f019ce4b3f6ec009f3c"
        }
      ]
    }
  ]
}
