{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "kltrgtvdevbihbmiyt3w5dggpy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 7186,
          "sha512": "bb9d694739795af9cab9e0f3cc82bf96b06b1b7b7b0848dde74ebccc6d37546c6037253cdaf9c2d4ff8dc95baf5e029c83f5fa2fc865c5cda9414b3b79e51459",
          "sha256": "ab58ba74efbf674b2ae3a6113dd6c3b52c71aea07bb464f72d3b56cb6a6941d1",
          "sha1": "410c3a2f4acd6e351573461a368644b133dd08dd",
          "md5": "6289e2dcecc5ef6d5d88690184ea8599"
        }
      ]
    }
  ]
}
