{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q3e2rgg2l5byhb7nda4kjixyhm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 5745,
          "sha512": "944e279d702578ff2316f1d34b74f655706db440fc8c09f67384a9975991b1840df90c3deea37faa02dbf31f3ffccb41f26a51201755cbd26c62d11ec9854c67",
          "sha256": "62c9e83909a56d9db598a8826c3bc8596a4948804442cffe76e17e57a4d55e78",
          "sha1": "3f0bbc2e36f9976773775e1426d011d63f4fb8d9",
          "md5": "872b4836d0b09c90dd2e08add63db684"
        }
      ]
    }
  ]
}
