{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "bwv26mi7wncxhccohujjnirfg4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 6933,
          "sha512": "d6a701286bd6c8c8f6900e6f5633db4aa18745e0d54ebae48ad1a568ec2058df65c7be5d29b288654c649d312dda75e2c5e5dc1563e213cbdc85eef6e12de2a7",
          "sha256": "bfb3059c5428f774b8f65329497a9d79327e1e3cbb0edc89a5117744962624ff",
          "sha1": "90e377c4d5e112bbd7c335113744e8145dffaecd",
          "md5": "2a82e606a704179213fd7f6d811a61e9"
        }
      ]
    }
  ]
}
