{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "m7attuko7vcgfgg46equzi2x2u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 5353,
          "sha512": "d119ba4e19737f30e30b977b14fbbaff5c5e1e6429066725b30a81d080034aa2c1571375bb246350924d5c201745eda9df792928b85937f12458af3cc5cc54c5",
          "sha256": "b359d7faffe5dc32600af4f8db7e0037ca971fbf2ee47d147e178449acc20b18",
          "sha1": "9f1422546789d04de8611930b9a71104f703a74f",
          "md5": "cc6bcabdf62566b1dcb133569238103f"
        }
      ]
    }
  ]
}
