{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "uq7ommsvp5guxexm5cq4ktna7y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 8035,
          "sha512": "04c57a61a31a4d3e0bb4327019e3825c8be4eca6d772193c65697008546f24d99061547d50ae2e31fa24e27087568ff0996cb313a3c86efd5518e12f409405ec",
          "sha256": "86b089c524abb9798d0754fbeae5f09205f0de524fb28740f0228d0004be6563",
          "sha1": "ccacbc26f2e57dd5dbbbaaaf8313bd4619fc5997",
          "md5": "d795bf879a03bb2ba379c1947db3540c"
        }
      ]
    }
  ]
}
