{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "uhl34nmw45ctpfyf3qpxalywlm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 7185,
          "sha512": "312e2c77981c18f4598a3e432f9ae0e26d87c0d55ab3138163613093653457fbf61d7493ac2015a8203c47874aa57361bca3a12b865f523d989d86258f7d47f6",
          "sha256": "7021b077ac7fc19ab864001ebf87446528957bb7d2dde94cc155d87896ec711f",
          "sha1": "a813bb26757fcf9bbae904488358a44fab0651e2",
          "md5": "ccc03e40f713c5d2872cb666425b0632"
        }
      ]
    }
  ]
}
