{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6bvzy6ueanetjgcafacnxzaapa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 7749,
          "sha512": "c5a47d0c41d1cafabd746d478ae7e39dd6bb6bf09e710796148cd585faa9cbaaf7db018a7ccf7ecc9ce73f5213eddc485b8b76aa55262de7fad0f4ec5cc28ae0",
          "sha256": "eae6e31c8725e1e5d21644138fc642bf634641faf4e33b36243fe776c9fe7ead",
          "sha1": "0cd9b503947588ece9f193682b56619c3fc1de41",
          "md5": "70804e37238fcb0d8f4fa6d6456a3430"
        }
      ]
    }
  ]
}
