{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5bzl6lpmkjc5npvscs26gj5b7u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 6882,
          "sha512": "76bdde4c08cbce52a1e324b2e8c42efaab22ca035b3e72fd35afde36f5330fd5656f7e9afa22587e97afe890fc39a3c88171277220ccabb87ad3554a4d1fb239",
          "sha256": "93f77afb4f9027367733467a1e00fb5f6049a0887f4e84e7e4548c0846ec1c47",
          "sha1": "72c882c158faeb3aa27b4e5de738bd4613ed8f09",
          "md5": "a420da4d7cf70bfc8104a12a6cbe540b"
        }
      ]
    }
  ]
}
