{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop-macos/0.0.1-SNAPSHOT/cinterop-macos-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop-macos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ifh4kenyvjenhdje3a3eqlo2km"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "url": "cinterop-metadata-0.0.1-SNAPSHOT.jar",
          "size": 7186,
          "sha512": "08ccfa9f9af8ae2bdef2a3759488b0e935623129331b97b6233112d840fea14e058677aac6c4bedfbf92c80e1f597cbc05f5fec293d67b9a7bdac6f9c6da57f4",
          "sha256": "4896bf985b1b4226db79edb3edf69de985f3f7decc6b7d41cd6ce884ce7e73bf",
          "sha1": "04bb1abe9fd5bae2bdac6a96135413753721ea75",
          "md5": "fa3a1dbf58c0acd2e3dc54cc283c59d6"
        }
      ]
    }
  ]
}
