{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lztqx75agbddbhe2qy3uqras4y"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-api-debug.aar",
          "url": "runtime-api-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 5537,
          "sha512": "5f5d0b7e3810403b03cc23d515f76b76eb2eb21c7c463a0bdc7a428380eff7052d49aa5a74164e57657346d00f263587de3d8f3f31ed11b31cb3579584e45b9f",
          "sha256": "7cd3d56b4b1b6a80f363c28a23a761faf8bbcc2ccf997f4594052ebb4ed55346",
          "sha1": "da389435799e7e08bcfeb0904306f714adac9b8e",
          "md5": "5d3e64ac002b3b94bbbb9c318329c1ee"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-debug.aar",
          "url": "runtime-api-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 5537,
          "sha512": "5f5d0b7e3810403b03cc23d515f76b76eb2eb21c7c463a0bdc7a428380eff7052d49aa5a74164e57657346d00f263587de3d8f3f31ed11b31cb3579584e45b9f",
          "sha256": "7cd3d56b4b1b6a80f363c28a23a761faf8bbcc2ccf997f4594052ebb4ed55346",
          "sha1": "da389435799e7e08bcfeb0904306f714adac9b8e",
          "md5": "5d3e64ac002b3b94bbbb9c318329c1ee"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
