{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "bwv26mi7wncxhccohujjnirfg4"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-debug.aar",
          "url": "cinterop-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 7053469,
          "sha512": "89c28b56591a1f70fdc854796cdc337536aff3506dda4507448fbb6eaf54c5df66354801f03e1d754231b66f90cd867659e721136210364559b909017b1a4eba",
          "sha256": "7dc5b36a3e17b1c81eecc71e74ad2035f35fd5319449e5667b0157ef1a05830d",
          "sha1": "fa74906e92cf7f4777c5f450883899dd4b53684e",
          "md5": "bb5d30b213f5d13bebe126460ac2346f"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-debug.aar",
          "url": "cinterop-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 7053469,
          "sha512": "89c28b56591a1f70fdc854796cdc337536aff3506dda4507448fbb6eaf54c5df66354801f03e1d754231b66f90cd867659e721136210364559b909017b1a4eba",
          "sha256": "7dc5b36a3e17b1c81eecc71e74ad2035f35fd5319449e5667b0157ef1a05830d",
          "sha1": "fa74906e92cf7f4777c5f450883899dd4b53684e",
          "md5": "bb5d30b213f5d13bebe126460ac2346f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
