{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "kltrgtvdevbihbmiyt3w5dggpy"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-debug.aar",
          "url": "cinterop-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 7056032,
          "sha512": "a55c8fd60c09e6dcccecb96afe97d90100654b6fd84d03ca38ff3655d983d0bb7f064ce8d52f7428692e8e78ebc9c371a1de6f95552d9411ecc868df5444aed8",
          "sha256": "16a5b0d86532718fda60ce5a06827d7eb1fdde873d3889b0a9ae26633f60bc61",
          "sha1": "52633395b677a16094946395f57e03d2e22c9fb0",
          "md5": "b71a38ad6a00c3f73252747885573b0b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-debug.aar",
          "url": "cinterop-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 7056032,
          "sha512": "a55c8fd60c09e6dcccecb96afe97d90100654b6fd84d03ca38ff3655d983d0bb7f064ce8d52f7428692e8e78ebc9c371a1de6f95552d9411ecc868df5444aed8",
          "sha256": "16a5b0d86532718fda60ce5a06827d7eb1fdde873d3889b0a9ae26633f60bc61",
          "sha1": "52633395b677a16094946395f57e03d2e22c9fb0",
          "md5": "b71a38ad6a00c3f73252747885573b0b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
