{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "uhl34nmw45ctpfyf3qpxalywlm"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-debug.aar",
          "url": "cinterop-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 7056040,
          "sha512": "fff6dcaa4d725dd4d55e5ee672bb9cb01e91923797c1364639b18590fdd15690c39c385cb255fe59afc11449cd698f4bc507390db91f9bd0d70eef5b41385216",
          "sha256": "5b0c38b65805b176f148b5f43a40cc6216c095be774676be40127d2f6d7c27b5",
          "sha1": "9d0ea6dbb8094740d6b754673d292b64503734e7",
          "md5": "902e2007e0d9ebaae0d39b77ff7f007c"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-debug.aar",
          "url": "cinterop-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 7056040,
          "sha512": "fff6dcaa4d725dd4d55e5ee672bb9cb01e91923797c1364639b18590fdd15690c39c385cb255fe59afc11449cd698f4bc507390db91f9bd0d70eef5b41385216",
          "sha256": "5b0c38b65805b176f148b5f43a40cc6216c095be774676be40127d2f6d7c27b5",
          "sha1": "9d0ea6dbb8094740d6b754673d292b64503734e7",
          "md5": "902e2007e0d9ebaae0d39b77ff7f007c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
