{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "uhl34nmw45ctpfyf3qpxalywlm"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-release.aar",
          "url": "cinterop-android-0.0.1-SNAPSHOT.aar",
          "size": 4611206,
          "sha512": "dbab9238ad517ad97b5d47be9ece316aa008fe3e057edace732ff0c6347e2f3c63c2458e0712430f30cb1d9a3b01fbc14f58eea354fed8ea5057b63cfe04d259",
          "sha256": "400fb8409bbee74e8ee1ef48d1eb094bc481fdaecb0f6470f760114289ba9f2d",
          "sha1": "a5e1021a5d2dd638c996d6e1656ff70b3fec9ed9",
          "md5": "212815f9a398b0fd2a6c469f6147f1b1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-release.aar",
          "url": "cinterop-android-0.0.1-SNAPSHOT.aar",
          "size": 4611206,
          "sha512": "dbab9238ad517ad97b5d47be9ece316aa008fe3e057edace732ff0c6347e2f3c63c2458e0712430f30cb1d9a3b01fbc14f58eea354fed8ea5057b63cfe04d259",
          "sha256": "400fb8409bbee74e8ee1ef48d1eb094bc481fdaecb0f6470f760114289ba9f2d",
          "sha1": "a5e1021a5d2dd638c996d6e1656ff70b3fec9ed9",
          "md5": "212815f9a398b0fd2a6c469f6147f1b1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
