{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cinterop/0.0.1-SNAPSHOT/cinterop-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "cinterop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6jiry4a3indwzhd2gt6t5oxrei"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-release.aar",
          "url": "cinterop-android-0.0.1-SNAPSHOT.aar",
          "size": 4608664,
          "sha512": "f1cdb60c7f7658ecc203473605fdad0552960ef959ce0fdc198500ab7bcf56dbd82922d2cf7667f2b505c9ec5a7124aad25922f6083402ea1d73ece01f36b62f",
          "sha256": "b0373be11489be0f500998ce4e14529e646d764ef0369b3e68c74b742e8d43c2",
          "sha1": "cbda888b95ef6468a0a41166f89ca5bbc36238c7",
          "md5": "5e78a8d0e32a94d2d40558a7d9cf14f1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "jni-swig-stub",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "cinterop-release.aar",
          "url": "cinterop-android-0.0.1-SNAPSHOT.aar",
          "size": 4608664,
          "sha512": "f1cdb60c7f7658ecc203473605fdad0552960ef959ce0fdc198500ab7bcf56dbd82922d2cf7667f2b505c9ec5a7124aad25922f6083402ea1d73ece01f36b62f",
          "sha256": "b0373be11489be0f500998ce4e14529e646d764ef0369b3e68c74b742e8d43c2",
          "sha1": "cbda888b95ef6468a0a41166f89ca5bbc36238c7",
          "md5": "5e78a8d0e32a94d2d40558a7d9cf14f1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../cinterop-metadata/0.0.1-SNAPSHOT/cinterop-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "cinterop-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
