{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "vnecmkkpgvhrlpxciy5mealhky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 109510,
          "sha512": "68588710ace2cef6cc458c983f78aa42037605f93f2af9fdb6a3a976aee2d5568dc27593d96d6ab0173d611b4226e895ab854e4e60cbe77c35163299cade563b",
          "sha256": "4f3e6bc1e71c2f1a3b558cdea2d1a823fe5596204773578ec7370b1237aa4d4d",
          "sha1": "66eeed3e19edd1d9478c39ce0a6b2071a6c3ef6b",
          "md5": "668bfe7a45b36ac3aae21000e3eccb10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 109510,
          "sha512": "68588710ace2cef6cc458c983f78aa42037605f93f2af9fdb6a3a976aee2d5568dc27593d96d6ab0173d611b4226e895ab854e4e60cbe77c35163299cade563b",
          "sha256": "4f3e6bc1e71c2f1a3b558cdea2d1a823fe5596204773578ec7370b1237aa4d4d",
          "sha1": "66eeed3e19edd1d9478c39ce0a6b2071a6c3ef6b",
          "md5": "668bfe7a45b36ac3aae21000e3eccb10"
        }
      ]
    }
  ]
}
