{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fk47hhp4wbad3eupfhvtksvz2i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 133596,
          "sha512": "644518d17c06a46816fa4e789bc85b94c62f5e5d3d37bd71ab41b07dca7dda240a3b167166ee22d94f436962e42bcdae0d91efcd1a99ee4186a50ad9af1ad695",
          "sha256": "e92af550b95232c6606bae7fc7b14eba084606fa90a8ae8e29bbe9db8017703f",
          "sha1": "ddc8688ba5b922458ec56a64d99fdec1a6a48066",
          "md5": "99ab6fa2caa394a2fa82fc7a25e2aacc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 133596,
          "sha512": "644518d17c06a46816fa4e789bc85b94c62f5e5d3d37bd71ab41b07dca7dda240a3b167166ee22d94f436962e42bcdae0d91efcd1a99ee4186a50ad9af1ad695",
          "sha256": "e92af550b95232c6606bae7fc7b14eba084606fa90a8ae8e29bbe9db8017703f",
          "sha1": "ddc8688ba5b922458ec56a64d99fdec1a6a48066",
          "md5": "99ab6fa2caa394a2fa82fc7a25e2aacc"
        }
      ]
    }
  ]
}
