{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "bwv26mi7wncxhccohujjnirfg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 117955,
          "sha512": "e26fe07aa5137761b7c3a141e5c686e531ef2d13b43d961a9a0206be4ecde56bfbf2bd4fe69b48ac1dc93f0389b0add2167118bfc694b001d34628b2d51cf436",
          "sha256": "0c4e4843527a228a778be18fafc6f2bb379ae097f09de4935e2eda7fbf5a520b",
          "sha1": "cfa010eed1e5f44984feb41c6338e4999d495777",
          "md5": "b6e77b51f9149ee971da658aa6c688f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 117955,
          "sha512": "e26fe07aa5137761b7c3a141e5c686e531ef2d13b43d961a9a0206be4ecde56bfbf2bd4fe69b48ac1dc93f0389b0add2167118bfc694b001d34628b2d51cf436",
          "sha256": "0c4e4843527a228a778be18fafc6f2bb379ae097f09de4935e2eda7fbf5a520b",
          "sha1": "cfa010eed1e5f44984feb41c6338e4999d495777",
          "md5": "b6e77b51f9149ee971da658aa6c688f6"
        }
      ]
    }
  ]
}
