{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "somvrmu74revpa67xwwsm5fbn4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 118573,
          "sha512": "838c78a53df7753dc0d4f37dc82a9a9e9b27f15cd9b26db651faa3b4c317b96f6a7eac538cc9ee0bfaffb651a107bc00215e76857acc5ee115a590638c170bbe",
          "sha256": "05e086efa307f0a154a144e9b15dfd7f322352d18a2fdcf656e069d65e2c08bb",
          "sha1": "0238d0af5a541555cdb44dfb342d89dadd777688",
          "md5": "f383bb703f805ec10c250bd6b1facf42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 118573,
          "sha512": "838c78a53df7753dc0d4f37dc82a9a9e9b27f15cd9b26db651faa3b4c317b96f6a7eac538cc9ee0bfaffb651a107bc00215e76857acc5ee115a590638c170bbe",
          "sha256": "05e086efa307f0a154a144e9b15dfd7f322352d18a2fdcf656e069d65e2c08bb",
          "sha1": "0238d0af5a541555cdb44dfb342d89dadd777688",
          "md5": "f383bb703f805ec10c250bd6b1facf42"
        }
      ]
    }
  ]
}
