{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "m7attuko7vcgfgg46equzi2x2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 109510,
          "sha512": "a6e3bb500e4bc5629405714892ab866889f332b06c23fcc1ed9489f87034ed078dd83d35e688ca943f5ab69c6663a50c5a40730c3cc6853ce8c0129f270f28d3",
          "sha256": "8e6234a14455e0c55719df7d40983cec62afc0b1d944703038ed547b9360e3b0",
          "sha1": "673a21bc4f9b950df0cf3ae36e990c7aaa3d068f",
          "md5": "5454d77b68bb7337db3e19d676bdb51d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 109510,
          "sha512": "a6e3bb500e4bc5629405714892ab866889f332b06c23fcc1ed9489f87034ed078dd83d35e688ca943f5ab69c6663a50c5a40730c3cc6853ce8c0129f270f28d3",
          "sha256": "8e6234a14455e0c55719df7d40983cec62afc0b1d944703038ed547b9360e3b0",
          "sha1": "673a21bc4f9b950df0cf3ae36e990c7aaa3d068f",
          "md5": "5454d77b68bb7337db3e19d676bdb51d"
        }
      ]
    }
  ]
}
