{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6jiry4a3indwzhd2gt6t5oxrei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 117951,
          "sha512": "9a0aec14d826d0fbf90d1978bac2bbcdd1373204fbcf429e57ac209479d08d32a9fe5ae01fc93a573a2e37afeca512fa5ae39c2740452d80abb937858dcfedf0",
          "sha256": "e9e601657667354bada94a1855f28a1a8dceaf19258bb5f2a1dfb7fb03a413ee",
          "sha1": "39bd7cac9da74e550ac10172bf8c0d1f843a71be",
          "md5": "23a228c9c4327fcc2e7f54127d5f67ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 117951,
          "sha512": "9a0aec14d826d0fbf90d1978bac2bbcdd1373204fbcf429e57ac209479d08d32a9fe5ae01fc93a573a2e37afeca512fa5ae39c2740452d80abb937858dcfedf0",
          "sha256": "e9e601657667354bada94a1855f28a1a8dceaf19258bb5f2a1dfb7fb03a413ee",
          "sha1": "39bd7cac9da74e550ac10172bf8c0d1f843a71be",
          "md5": "23a228c9c4327fcc2e7f54127d5f67ae"
        }
      ]
    }
  ]
}
