{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ifh4kenyvjenhdje3a3eqlo2km"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 139839,
          "sha512": "539ee9f98e124762718a7a996c1220b883fc4ec236812762e7233006afa760fafbf178f179e5bf8ac0aa0c68378c190c473b028b53c1b89c12b5f95981a70627",
          "sha256": "c043065fb414307ae7516308b0b937ab05a895ea5cbfc8c6b04ce3e519b7fbac",
          "sha1": "05ad91b274eaafd61557034da77199b00142d6b2",
          "md5": "37752aef10ec40892539a131a4b3a279"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 139839,
          "sha512": "539ee9f98e124762718a7a996c1220b883fc4ec236812762e7233006afa760fafbf178f179e5bf8ac0aa0c68378c190c473b028b53c1b89c12b5f95981a70627",
          "sha256": "c043065fb414307ae7516308b0b937ab05a895ea5cbfc8c6b04ce3e519b7fbac",
          "sha1": "05ad91b274eaafd61557034da77199b00142d6b2",
          "md5": "37752aef10ec40892539a131a4b3a279"
        }
      ]
    }
  ]
}
