{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6egzcbczdzd5dhwgb5brpaofaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 109510,
          "sha512": "cc08e0bc1270c0bbfcfc4deb9f240949915450529a66fabf038e889738b599525fa796db9929d677d951a4b15e75d60d3f9123e2cf318a2bdc9e8efa05ebb34f",
          "sha256": "9cb57067510406c4ac9efd8ccb0f29cf90a20795964910d982b4e05aca661996",
          "sha1": "3d6f990a452ebb9274963864a716684ce0bebc02",
          "md5": "2fefeeef7bddc1bb92f79debaebf4fb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "url": "plugin-compiler-0.0.1-SNAPSHOT.jar",
          "size": 109510,
          "sha512": "cc08e0bc1270c0bbfcfc4deb9f240949915450529a66fabf038e889738b599525fa796db9929d677d951a4b15e75d60d3f9123e2cf318a2bdc9e8efa05ebb34f",
          "sha256": "9cb57067510406c4ac9efd8ccb0f29cf90a20795964910d982b4e05aca661996",
          "sha1": "3d6f990a452ebb9274963864a716684ce0bebc02",
          "md5": "2fefeeef7bddc1bb92f79debaebf4fb4"
        }
      ]
    }
  ]
}
