{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-gradle",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jwlw7xylsne4xdduyohaekyupa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20-M1-63"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "url": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "size": 11659,
          "sha512": "1f889a1a94d43776eb81cb35e5eb57460c25fd30683f21706bd72aad7175d382165ff167c090705953ea5a94fb6fb7e6b1ff44bcb7640ee4386a39e894e67dcd",
          "sha256": "6b271f3f69a4a9c5578cabb503ddac5478823626bb0838b39dceb1e12b11d0c9",
          "sha1": "711a2d1b8068a3f74a1c2d4bbc2c0a912af00bbe",
          "md5": "4c538bd18109d90fe1cbdfaeb7dadceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20-M1-63"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "url": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "size": 11659,
          "sha512": "1f889a1a94d43776eb81cb35e5eb57460c25fd30683f21706bd72aad7175d382165ff167c090705953ea5a94fb6fb7e6b1ff44bcb7640ee4386a39e894e67dcd",
          "sha256": "6b271f3f69a4a9c5578cabb503ddac5478823626bb0838b39dceb1e12b11d0c9",
          "sha1": "711a2d1b8068a3f74a1c2d4bbc2c0a912af00bbe",
          "md5": "4c538bd18109d90fe1cbdfaeb7dadceb"
        }
      ]
    }
  ]
}
