{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "plugin-gradle",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "gxinkq7ql5ewtblyejiyu4labi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20-M1-63"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "url": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "size": 11659,
          "sha512": "42173ae5b4ee0548360891dfb5bb2a8117125b8a9365d5103682d087357a0736912a9c65f245eef84f76961551b1175570b948873d09f65c1ac19ac236905157",
          "sha256": "a1a5d305e85340c36ec1bfca66d88c86b5d80d9c43f69d8a7660c2c143b750ef",
          "sha1": "7697884e3438424862cdcfc42d9ac06dfee1723c",
          "md5": "a01d08bb17bb7cc356ff4870fe7b37de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20-M1-63"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "url": "plugin-gradle-0.0.1-SNAPSHOT.jar",
          "size": 11659,
          "sha512": "42173ae5b4ee0548360891dfb5bb2a8117125b8a9365d5103682d087357a0736912a9c65f245eef84f76961551b1175570b948873d09f65c1ac19ac236905157",
          "sha256": "a1a5d305e85340c36ec1bfca66d88c86b5d80d9c43f69d8a7660c2c143b750ef",
          "sha1": "7697884e3438424862cdcfc42d9ac06dfee1723c",
          "md5": "a01d08bb17bb7cc356ff4870fe7b37de"
        }
      ]
    }
  ]
}
