{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "gtko3sey4rcstpjkqkzlc6bzxu"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 32497,
          "sha512": "e8a65b458b15c8878023fd0357b1128d3912d48adb1ee1207b460f0c0235f8be6d71d783d0dd12e552782477eaa1dd62a520593a547ba08e0d2e1978ba7a99f7",
          "sha256": "464b54178874fd1a96896f402c679c7f355eb5a215edd21ab159db236360b6ce",
          "sha1": "8fd2374fc5fdc74646cd37ab9a5ef5807e296e9b",
          "md5": "926a060c4e8abefc18fb61cec87a59c6"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 32497,
          "sha512": "e8a65b458b15c8878023fd0357b1128d3912d48adb1ee1207b460f0c0235f8be6d71d783d0dd12e552782477eaa1dd62a520593a547ba08e0d2e1978ba7a99f7",
          "sha256": "464b54178874fd1a96896f402c679c7f355eb5a215edd21ab159db236360b6ce",
          "sha1": "8fd2374fc5fdc74646cd37ab9a5ef5807e296e9b",
          "md5": "926a060c4e8abefc18fb61cec87a59c6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
