{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "rzgj3lv7offm3momvbfwacf7de"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 49296,
          "sha512": "28b98ff74669d7e19b165a933bdd2c1c0ba9d7700bcc9fb48f621c743eafca794d356dc09b3846d1d6879c96bc6986a8a3522931e2a776a5e803c5e0f6f7bbc3",
          "sha256": "51dc09ed553caada675d2a493b30fd1771937159af9f4d00558a7b7595720abf",
          "sha1": "98d34226a100b4af42831c0791b48b32fc1ca694",
          "md5": "e108f836259bcd55ae81ae394ea38ac0"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 49296,
          "sha512": "28b98ff74669d7e19b165a933bdd2c1c0ba9d7700bcc9fb48f621c743eafca794d356dc09b3846d1d6879c96bc6986a8a3522931e2a776a5e803c5e0f6f7bbc3",
          "sha256": "51dc09ed553caada675d2a493b30fd1771937159af9f4d00558a7b7595720abf",
          "sha1": "98d34226a100b4af42831c0791b48b32fc1ca694",
          "md5": "e108f836259bcd55ae81ae394ea38ac0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
