{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5bzl6lpmkjc5npvscs26gj5b7u"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 48104,
          "sha512": "0543d0634cd5a7ae68032f0bdaa1a0f530def57e7d85a46b3a2ab11335ca1e661494686abd2f948c03e8147a1465f569d664a9d5e58e5b2e1df1b9408f12a49d",
          "sha256": "7b4273598c88dc2c1903756718c9e20d7a2ec3245b749e07f9fc5bae72674ead",
          "sha1": "9f7f186ff52b1975e53bbf7533395a4bec5b29cb",
          "md5": "9c87e7244ff259dfc9b773442629a917"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 48104,
          "sha512": "0543d0634cd5a7ae68032f0bdaa1a0f530def57e7d85a46b3a2ab11335ca1e661494686abd2f948c03e8147a1465f569d664a9d5e58e5b2e1df1b9408f12a49d",
          "sha256": "7b4273598c88dc2c1903756718c9e20d7a2ec3245b749e07f9fc5bae72674ead",
          "sha1": "9f7f186ff52b1975e53bbf7533395a4bec5b29cb",
          "md5": "9c87e7244ff259dfc9b773442629a917"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
