{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "mivlqka25ngh7cpqpg7nkmxgeq"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 25403,
          "sha512": "fb388e4726511c2e05cbeb617256bc73b03ba3e3b6c5e329342af94edfb1fecea1fedc3c7ccb8eadc38eba30b32a290446eab12a9b8829510610a06f720d5af8",
          "sha256": "29a43a3682dfeee0af38eb790df18a3b1836c9f72df32921d3e6e66640410159",
          "sha1": "f4514260e08bd5d512a185da4be37dd1c2e02691",
          "md5": "7404e500e7ab339dc47b4f63fc001144"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm.kotlin",
          "module": "cinterop",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "io.realm.kotlin",
          "module": "runtime-api",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "library-debug.aar",
          "url": "library-android-debug-0.0.1-SNAPSHOT.aar",
          "size": 25403,
          "sha512": "fb388e4726511c2e05cbeb617256bc73b03ba3e3b6c5e329342af94edfb1fecea1fedc3c7ccb8eadc38eba30b32a290446eab12a9b8829510610a06f720d5af8",
          "sha256": "29a43a3682dfeee0af38eb790df18a3b1836c9f72df32921d3e6e66640410159",
          "sha1": "f4514260e08bd5d512a185da4be37dd1c2e02691",
          "md5": "7404e500e7ab339dc47b4f63fc001144"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../library-metadata/0.0.1-SNAPSHOT/library-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
