{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "proci3g3ibbk3ozhbrxcts6k6y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-api-metadata-0.0.1-SNAPSHOT.jar",
          "url": "runtime-api-0.0.1-SNAPSHOT.jar",
          "size": 3507,
          "sha512": "8e1961c2a02a561b1c88df310e0fa1af2193c07eeb6aa8fdc5d354bfc591acca829858c2a840636f0f5fcb3b32e5a83dcd157203d4730a6e34ac47be37a61fc8",
          "sha256": "a5693b5d67a6b56fdd91c52b71b88d358efa8cf8845aa21d62e5d735d0cc5c85",
          "sha1": "ba3e50ed160188b56cce3a4a553740da68939ee2",
          "md5": "157dfddb7afa762432e83156387176c8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android-debug/0.0.1-SNAPSHOT/runtime-api-android-debug-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-android-debug",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android-debug/0.0.1-SNAPSHOT/runtime-api-android-debug-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-android-debug",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android/0.0.1-SNAPSHOT/runtime-api-android-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-android",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android/0.0.1-SNAPSHOT/runtime-api-android-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-android",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-ios/0.0.1-SNAPSHOT/runtime-api-ios-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-ios",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-api-jvm/0.0.1-SNAPSHOT/runtime-api-jvm-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-jvm",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-api-jvm/0.0.1-SNAPSHOT/runtime-api-jvm-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-jvm",
        "version": "0.0.1-SNAPSHOT"
      }
    },
    {
      "name": "macosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macos/0.0.1-SNAPSHOT/runtime-api-macos-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-macos",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
