{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lztqx75agbddbhe2qy3uqras4y"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-api-release.aar",
          "url": "runtime-api-android-0.0.1-SNAPSHOT.aar",
          "size": 5405,
          "sha512": "a36de52971831f0f9ca91888ee5c7d745559cb2ab997b81d01a514b325610a491e70e753ccd867e068ebb47a5f69b95013a4fd61123e9b8a27b9a7227021a0ff",
          "sha256": "49379584d170fd69e39f3348fa3a8ec905f0d8895798d4f606a4d39513064ac9",
          "sha1": "183d5d66175e2c07a893abd4b4fdc19861b14d49",
          "md5": "787915dfca4404c428a654e7fb804973"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api-release.aar",
          "url": "runtime-api-android-0.0.1-SNAPSHOT.aar",
          "size": 5405,
          "sha512": "a36de52971831f0f9ca91888ee5c7d745559cb2ab997b81d01a514b325610a491e70e753ccd867e068ebb47a5f69b95013a4fd61123e9b8a27b9a7227021a0ff",
          "sha256": "49379584d170fd69e39f3348fa3a8ec905f0d8895798d4f606a4d39513064ac9",
          "sha1": "183d5d66175e2c07a893abd4b4fdc19861b14d49",
          "md5": "787915dfca4404c428a654e7fb804973"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
