{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fc4grno7vbd6vfqxbuf7qv6mrm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "73c990e1af7191e4d3c0d32e93a7683d258ae98cbfceda5d5d9413dbf4c5100ec2e4be42e496cac61d914aa771b002a0c7f504f3d63c6c6d4962d1a876151ab2",
          "sha256": "13c90c7d0115bb6e22add57b206b525f7d81670eabe585cdada7409dade35e45",
          "sha1": "65b0d53bf366df14a17f29042fd61b563646c0c0",
          "md5": "3987ab2c8bd70d1ac64c26293212dc0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "73c990e1af7191e4d3c0d32e93a7683d258ae98cbfceda5d5d9413dbf4c5100ec2e4be42e496cac61d914aa771b002a0c7f504f3d63c6c6d4962d1a876151ab2",
          "sha256": "13c90c7d0115bb6e22add57b206b525f7d81670eabe585cdada7409dade35e45",
          "sha1": "65b0d53bf366df14a17f29042fd61b563646c0c0",
          "md5": "3987ab2c8bd70d1ac64c26293212dc0b"
        }
      ]
    }
  ]
}
