{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6jiry4a3indwzhd2gt6t5oxrei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "f04bb010a15b8ebad561489ded158e7e2180e9438120101f538ae8380555ce5b93b7bb38bdec5d65be2d64102c602d9ce031f7f44238b5f02ec57dba5d47d9e0",
          "sha256": "32777c3310f974e80a55b5e936010ff08aa4ed37c78548fa6d1b9bd2f120abaf",
          "sha1": "c17807e9eb54f318351bd2a5664cfe33826f916c",
          "md5": "9e85d1665dfe7e1d5feb4a12fd21264c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "f04bb010a15b8ebad561489ded158e7e2180e9438120101f538ae8380555ce5b93b7bb38bdec5d65be2d64102c602d9ce031f7f44238b5f02ec57dba5d47d9e0",
          "sha256": "32777c3310f974e80a55b5e936010ff08aa4ed37c78548fa6d1b9bd2f120abaf",
          "sha1": "c17807e9eb54f318351bd2a5664cfe33826f916c",
          "md5": "9e85d1665dfe7e1d5feb4a12fd21264c"
        }
      ]
    }
  ]
}
