{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "rbgo33tgjjfxvmc2mjwjxxajh4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "454df0031eb85eb0049ce20c90a40362f0b9c48d548e71edfa3942f8072d7a7de0cac338a6aeba3db7afa67f3859e224a6ba18561cbabc8d3e8f73815c251939",
          "sha256": "8807e7715939dc5db53073b2dbec7fff80a1341f950a21e2b174bcd843d08453",
          "sha1": "8677b63ac284dc1d8f7013d27e7858b4db227aa2",
          "md5": "71c72dade0c7b76195b41ff4e312225f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "454df0031eb85eb0049ce20c90a40362f0b9c48d548e71edfa3942f8072d7a7de0cac338a6aeba3db7afa67f3859e224a6ba18561cbabc8d3e8f73815c251939",
          "sha256": "8807e7715939dc5db53073b2dbec7fff80a1341f950a21e2b174bcd843d08453",
          "sha1": "8677b63ac284dc1d8f7013d27e7858b4db227aa2",
          "md5": "71c72dade0c7b76195b41ff4e312225f"
        }
      ]
    }
  ]
}
