{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fk47hhp4wbad3eupfhvtksvz2i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "bad979761e4db5a57761d0fdd9c9cee246617d32e130e59dd5d4eeb186e71149c99ff717b9895fbfdadfea3169b97b0f5c38d6e01bcfd4bc154bb527e854af2b",
          "sha256": "d4c10879aaac1d1d98231affcbb315d3e6398aebae27f3cd6d77faf3a90be8f6",
          "sha1": "bbda4f9630dcf0e1c8ae5e0081b4a1ea9aba3706",
          "md5": "1bec87926496001fe6c906f3f27569eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "bad979761e4db5a57761d0fdd9c9cee246617d32e130e59dd5d4eeb186e71149c99ff717b9895fbfdadfea3169b97b0f5c38d6e01bcfd4bc154bb527e854af2b",
          "sha256": "d4c10879aaac1d1d98231affcbb315d3e6398aebae27f3cd6d77faf3a90be8f6",
          "sha1": "bbda4f9630dcf0e1c8ae5e0081b4a1ea9aba3706",
          "md5": "1bec87926496001fe6c906f3f27569eb"
        }
      ]
    }
  ]
}
