{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "4dyxnyw7d5djnek6oe7u6ph634"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "5a30dc952d12df9350303fada68ed3234ee509809f9f1c7914286f2ed9daf248e98a1a40dcf884522c3cfd25fe853b1d7f960d11088448bbb95d984455b28356",
          "sha256": "f671029e3691c02cd6e8ffbec358c587016de8c0e25765e3fd6ad4db4f921a60",
          "sha1": "4ac544e0fc10e46a855580b0c76ca6277c74d919",
          "md5": "10d78e303d1617283b84cb8e3e42eea0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "5a30dc952d12df9350303fada68ed3234ee509809f9f1c7914286f2ed9daf248e98a1a40dcf884522c3cfd25fe853b1d7f960d11088448bbb95d984455b28356",
          "sha256": "f671029e3691c02cd6e8ffbec358c587016de8c0e25765e3fd6ad4db4f921a60",
          "sha1": "4ac544e0fc10e46a855580b0c76ca6277c74d919",
          "md5": "10d78e303d1617283b84cb8e3e42eea0"
        }
      ]
    }
  ]
}
