{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ifh4kenyvjenhdje3a3eqlo2km"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "45fabdebd7c506c8a439079a211dfc0ced75d64ed37004820ecdcdee9f4ec6e8569b8e387561edcd6dfa205777e93287f9b97ba2fe2f694184c7c0f7fba4f7e9",
          "sha256": "799b71915b7c39303a89eb21c888a039901ff2dffcc7993a2239af0011bf7fa0",
          "sha1": "c916fe0133eaef6d2c445b53cced7f8effae8be1",
          "md5": "d8b3bcfd7836be605a1878b06d968483"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21763,
          "sha512": "45fabdebd7c506c8a439079a211dfc0ced75d64ed37004820ecdcdee9f4ec6e8569b8e387561edcd6dfa205777e93287f9b97ba2fe2f694184c7c0f7fba4f7e9",
          "sha256": "799b71915b7c39303a89eb21c888a039901ff2dffcc7993a2239af0011bf7fa0",
          "sha1": "c916fe0133eaef6d2c445b53cced7f8effae8be1",
          "md5": "d8b3bcfd7836be605a1878b06d968483"
        }
      ]
    }
  ]
}
