{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q3e2rgg2l5byhb7nda4kjixyhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21702,
          "sha512": "c901a44726cb084f26a77cb00dbe638c9c5d2ba5bc96ad10cdaee6e9c6c79460f2c0dc6f556aaf62ff2194d71237d7117daa60172ce6e730d00779a8c9dd7228",
          "sha256": "527a03a86e6fd20b8a7d835ed9e8c3a030fec3998a46672a7c8098daa18da325",
          "sha1": "66ca788b23d21276df49704dadb7e4909619b61f",
          "md5": "a64c2bd7dc2bc3d19bee67ee08e6441a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 21702,
          "sha512": "c901a44726cb084f26a77cb00dbe638c9c5d2ba5bc96ad10cdaee6e9c6c79460f2c0dc6f556aaf62ff2194d71237d7117daa60172ce6e730d00779a8c9dd7228",
          "sha256": "527a03a86e6fd20b8a7d835ed9e8c3a030fec3998a46672a7c8098daa18da325",
          "sha1": "66ca788b23d21276df49704dadb7e4909619b61f",
          "md5": "a64c2bd7dc2bc3d19bee67ee08e6441a"
        }
      ]
    }
  ]
}
