{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm.kotlin",
    "module": "gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "m7attuko7vcgfgg46equzi2x2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 9845,
          "sha512": "9d68ce23256cb5157641737110ad49d482bab2cdf199a339b4af93ccd5f89492abbfbaa94bf08096bd24d2410a2a44183d50a5bece2dae1510270caf03bd66b4",
          "sha256": "62528d96521c26f86b160a39245d23665ca07ca5d634b66c2064033336cd087e",
          "sha1": "3286e38ceea961bbc665d29a68374c72b841d5a3",
          "md5": "a45011de651cf5f0afc67e6bf36bb471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 9845,
          "sha512": "9d68ce23256cb5157641737110ad49d482bab2cdf199a339b4af93ccd5f89492abbfbaa94bf08096bd24d2410a2a44183d50a5bece2dae1510270caf03bd66b4",
          "sha256": "62528d96521c26f86b160a39245d23665ca07ca5d634b66c2064033336cd087e",
          "sha1": "3286e38ceea961bbc665d29a68374c72b841d5a3",
          "md5": "a45011de651cf5f0afc67e6bf36bb471"
        }
      ]
    }
  ]
}
