{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "vcdovjfpurfhxbqb47bplm7tsm"
    }
  },
  "variants": [
    {
      "name": "macosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api.klib",
          "url": "runtime-api-macos-0.0.1-SNAPSHOT.klib",
          "size": 8348,
          "sha512": "8c90284914689ca9bee8d188fb9e66eb579558ccdd2ca0d3b7c43d38c205abe388eb98ce56fd4429f1fbc5e5566846b7418ade02477364be223b233cf0793140",
          "sha256": "ffef045eeb73d2abdca158ab72fe0a45b7903b3d52f6758145a66f9e800207d1",
          "sha1": "65a38c7bf46e45413e9d7fbf1ecc6d708f81edaf",
          "md5": "6a28b3eed28034ed8305456f30f7314d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
