{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/0.0.1-SNAPSHOT/runtime-api-0.0.1-SNAPSHOT.module",
    "group": "io.realm.kotlin",
    "module": "runtime-api",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zugs2ii6xjatxdegy4dcn4xjhi"
    }
  },
  "variants": [
    {
      "name": "macosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-api.klib",
          "url": "runtime-api-macos-0.0.1-SNAPSHOT.klib",
          "size": 9126,
          "sha512": "19f9573f341b9a5c25b94e83c7fe5649d8207ee411e27d00b60a631e6b7fd1ded994242096275e77d8bed19eaa420a0f83d900b668bf2a96a6125a2a09f94ca6",
          "sha256": "34ff2deac7afc5050983f571a8b3da94a1b377e9f45156afa84ec76b3b42e5f0",
          "sha1": "38fff1ea83dc4ff632c855f87c6fe12f03d7e900",
          "md5": "a83602c1af0dc71d414f621734c0ff82"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-api-metadata/0.0.1-SNAPSHOT/runtime-api-metadata-0.0.1-SNAPSHOT.module",
        "group": "io.realm.kotlin",
        "module": "runtime-api-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
